### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by V3nomAnc3r** [AzerothJS/AzerothAPI#40]
Hi, i have problem, when i use proxy to send request to the api, i get this warning

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at :3000/auth/signup. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel)`

**Comment by Helias** [comment]
It's strange, because I think that I solved this here https://github.com/AzerothJS/AzerothAPI/pull/3

**Comment by IntelligentQuantum** [comment]
@V3nomAnc3r Are you sure?! What operating system do you use?

I tested this api on Debian 10, Archlinux, windows 2012 it works fine! (VPS)

![Arena Stats](https://user-images.githubusercontent.com/14080516/70566531-7e438a80-1ba9-11ea-8823-f5ccf8ddadf2.png)
![Server Status](https://user-images.githubusercontent.com/14080516/70566639-b0ed8300-1ba9-11ea-913e-102562c634f0.png)

**Comment by V3nomAnc3r** [comment]
Ubuntu 18.04, https://github.com/AzerothJS/AzerothAPI/commit/0f96597e8729aa6edffa806118ad84ee8751041d

**Comment by IntelligentQuantum** [comment]
Open port 3000 if you are using firewall

**Comment by V3nomAnc3r** [comment]
Thank you! It works perfect.
