### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by bardiademon** [AzerothJS/AzerothAPI#5]
Hello can you add coin and point for remote entity?
and please add phone, first name, last name, birthday for sign up account.

like this https://eu.battle.net/account/creation/en-us/

for example with phone we can create a custom module for active account.

**Comment by IntelligentQuantum** [comment]
hi @bardiademon please test https://github.com/AzerothJS/AzerothAPI/pull/6

**Comment by bardiademon** [comment]
Everything looks fine.
but you need to add refound coin to this line
https://github.com/IntelligentQuantum/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L27777

**Comment by IntelligentQuantum** [comment]
Yes! thanks i forgot that xD

**Comment by IntelligentQuantum** [comment]
@bardiademon please test [Coin](https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/bd7255596ee774f81928a540fed48ffb7a69d187)

**Comment by bardiademon** [comment]
Pass the test and work as expected
