### ISSUE TITLE
Bug RecoveryItem

### ISSUE THREAD

**Issue by MarkMBarnett** [AzerothJS/AzerothAPI#9]
recovery item does not work

`[ExceptionsHandler] ER_NO_SUCH_TABLE: Table 'characters.azeroth_mail' doesn't exist +552242ms
QueryFailedError: ER_NO_SUCH_TABLE: Table 'characters.azeroth_mail' doesn't exist`

**Comment by IntelligentQuantum** [comment]
[RecoveryItem Part 1](https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/ec8701684456edf2f2d6aa5116a14f2f82f68b3d)
[Recovery Item Part 2](https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/c520a784d92c722662623df44dfb88964b4281d4)
[azeroth_mail.sql](https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/9016fcbcd864b27cc4e983741c10c2aa86085357)

Did you add these to your core?

**Comment by MarkMBarnett** [comment]
It's working fine now. Thank you
